version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-flask:latest
    container_name: flask_app_container
    ports:
      - "8218:8218"
    volumes:
      - .:/app 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=automated_deploy
      - DB_USER=thiago
      - DB_PASS=123

    depends_on:
      - db 
    networks:
      - app-network 

db:
    image: postgres:15-alpine
    container_name: postgres_db_container
    environment: 
      POSTGRES_DB: automated_deploy
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: 123
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "8219:5432"
    networks: 
      - app-network

volumes:
  postgres_data: 

networks:
  app-network:
    driver: bridge 
