# .github/workflows/deploy.yml

name: CI/CD Deploy Automatizado Fatec

# Define quando o workflow será acionado
on:
  push:
    branches:
      - main # Aciona em pushes para a branch main
  workflow_dispatch: # Permite acionar manualmente pela interface do GitHub

jobs:
  build-and-push-docker-image:
    name: Build e Push Imagem Docker
    runs-on: ubuntu-latest # O job rodará em uma máquina virtual Ubuntu fornecida pelo GitHub

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Action para baixar o código do seu repositório

      - name: Configurar QEMU (para build multi-arquitetura, opcional mas bom)
        uses: docker/setup-qemu-action@v3

      - name: Configurar Docker Buildx (builder avançado)
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: thiagoresende/app-flask-fatec:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
